[package]
name = "wosim"
version = "0.1.0"
authors = ["Edgar Geier <egeier@rhrk.uni-kl.de>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
workspace = ".."
edition = "2018"

[dependencies]
ash-window = "0.6"
copypasta = "0.7.1"
egui = "0.11.0"
nalgebra = "0.26.1"
webbrowser = "0.5.5"
winit = "0.24"
common = { path = "../common/base", package = "wosim-common-base" }
vulkan = { path = "../common/vulkan", package = "wosim-common-vulkan" }
server = { path = "../server", package = "wosim-server" }

[build-dependencies]
build = { path = "../common/build", package = "wosim-common-build" }
