packageExtensions:
  '@nuxt/content@*':
    dependencies:
      json5: ^2.1.2
  '@nuxt/types@*':
    dependencies:
      webpack: ^5.39.1
  '@nuxt/typescript-build@*':
    dependencies:
      webpack: ^5.39.1
  '@nuxt/vue-app@*':
    dependencies:
      core-js: ^3.14.0
  '@nuxtjs/eslint-module@*':
    dependencies:
      webpack: ^5.39.1
  '@nuxtjs/stylelint-module@*':
    dependencies:
      webpack: ^5.39.1
  '@nuxtjs/vuetify@*':
    dependencies:
      vue: ^2.6.14
      vue-template-compiler: ^2.6.12
      webpack: ^5.39.1
  deasync@*:
    dependencies:
      node-gyp: ^8.1.0
  eslint-plugin-nuxt@*:
    dependencies:
      eslint: ^7.29.0
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      vue-template-compiler: ^2.6.12
  nuxt@*:
    dependencies:
      consola: ^2.15.3
