[package]
name = "wosim-server"
version = "0.1.0"
authors = ["Edgar Geier <egeier@rhrk.uni-kl.de>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
workspace = ".."
edition = "2018"

[dependencies]
common = { path = "../common/base", package = "wosim-common-base" }
vulkan = { path = "../common/vulkan", package = "wosim-common-vulkan" }

[[bin]]
name = "wosim-server"
