[package]
name = "wosim-server"
version = "0.1.0"
authors = ["Edgar Geier <egeier@rhrk.uni-kl.de>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
workspace = ".."
edition = "2018"

[dependencies]
actor = { path = "../common/actor", package = "wosim-common-actor" }
ctrlc = "3.1.9"
env_logger = "0.8.3"
log = "0.4.14"
net = { path = "../common/net", package = "wosim-common-net" }
quinn = "0.7.2"
serde = { version = "1.0.125", features = ["derive"] }
tokio = { version = "1.5.0", features = ["rt", "rt-multi-thread", "time"] }
util = { path = "../common/util", package = "wosim-common-util" }
vulkan = { path = "../common/vulkan", package = "wosim-common-vulkan" }
webpki = "0.21"

[[bin]]
name = "wosim-server"
