[package]
name = "wosim-util"
version = "0.1.0"
authors = ["Edgar Geier <egeier@rhrk.uni-kl.de>"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
workspace = ".."
edition = "2018"
publish = false

[dependencies]
cfg-if = "1"
memmap = "0.7"

[features]
embed-assets = []
