name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version number'
        required: true
      msi_version:
        description: 'MSI version number'
        required: true

env:
  INPUT_VERSION: ${{ github.event.inputs.version }}
  INPUT_MSI_VERSION: ${{ github.event.inputs.msi_version }}

jobs:
  create-release-draft:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Create release draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create v$INPUT_VERSION --title v$INPUT_VERSION --draft
        shell: bash

  build:
    needs: create-release-draft

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [14]
        rust: [stable]

    environment:
      name: release

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Install webkit2gtk (ubuntu only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libgtksourceview-3.0-dev webkit2gtk-4.0 libappindicator3-dev

      - name: Setup node env
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Setup rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache rust dependencies
        uses: Swatinem/rust-cache@v1
        with:
          working-directory: src-tauri

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache node_modules
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn

      - name: Build release
        env:
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_PUBLIC_KEY: dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDdDQzA1QUVGNkQwMTI2QQpSV1JxRXREMnJnWE1CMFZkRC9FYVd2TDVpNGtLQW8xNGR3a2tjWWhaK1Z2dGlnOXZYcDEyd0ZtdQo=
        run: yarn build:release

      - name: Upload release files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload v$INPUT_VERSION release/*
        shell: bash
