name: Rust

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Check formatting
        run: cargo fmt --all --verbose
      - name: Check code
        run: cargo clippy --workspace --verbose -- -D warnings
      - name: Build
        run: cargo build --workspace --verbose
      - name: Run tests
        run: cargo test --workspace --verbose
